### PR TITLE
new feature added save button hide and show.

### PR DESCRIPTION
**Pull request by mayurpitroda96**
new feature added save button hide and show.

### CODE REVIEW

**Comment by psk907** [comment]
@mayurpitroda96 can you also attach screenshots of the widget with and without the save button shown? 
Just to confirm that things are working before I can merge your PR.

**Comment by mayurpitroda96** [comment]
Yes sure i will send you a screenshot and video recorder around 6pm.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by mayurpitroda96** [comment]
mayur pitroda has shared OneDrive files with you. To view them, click the links below.
<https://1drv.ms/u/s!AufnOa79Nrahi0rcxjFkr8RoX4mX>
[https://r1.res.office365.com/owa/prem/images/dc-mpg_20.png]<https://1drv.ms/u/s!AufnOa79Nrahi0rcxjFkr8RoX4mX>
Screen Recording 2021-10-01 at 7.08.26 PM.mov<https://1drv.ms/u/s!AufnOa79Nrahi0rcxjFkr8RoX4mX>

<https://1drv.ms/u/s!AufnOa79Nrahi0tzXORzaNMsNa-G>
[https://r1.res.office365.com/owa/prem/images/dc-png_20.png]<https://1drv.ms/u/s!AufnOa79Nrahi0tzXORzaNMsNa-G>
Simulator Screen Shot - iPhone 6s - 2021-10-01 at 19.08.54.png<https://1drv.ms/u/s!AufnOa79Nrahi0tzXORzaNMsNa-G>

<https://1drv.ms/u/s!AufnOa79Nrahi0yHUFrU8mGgSAa7>
[https://r1.res.office365.com/owa/prem/images/dc-png_20.png]<https://1drv.ms/u/s!AufnOa79Nrahi0yHUFrU8mGgSAa7>
Simulator Screen Shot - iPhone 6s - 2021-10-01 at 19.09.02.png<https://1drv.ms/u/s!AufnOa79Nrahi0yHUFrU8mGgSAa7>

________________________________

**Comment by psk907** [comment]
Looking good @mayurpitroda96 . I shall merge these now.
Your changes also resolve the issue #6

**Pull request merged**
